#!/bin/bash
gitTop=$( git rev-parse --show-toplevel 2> /dev/null )
[[ "$gitTop" == "" ]] && exit 0
gitRemotes="$gitTop/.gitremotes"
[[ "$( git remote -v | grep -v origin )" == "" ]] && exit 0
git remote -v | grep -v origin > "$gitRemotes"
git add --all
